stages:
  - echo
  - build

echo-job:
  tags:
    - xt
  stage: echo
  script:
    - echo "Hello, world213!"
  only:
    - test
    - pre
    - release

build-job:
  tags:
    - xt
  stage: build
  script:
    - echo "Building version ${HOST}..."
  only:
    - test
    - pre
    - release
```
