/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseForm: typeof import('./src/components/base-form/index.vue')['default']
    BaseModal: typeof import('./src/components/base-modal/index.vue')['default']
    Content: typeof import('./src/components/content/index.vue')['default']
    DownloadTable: typeof import('./src/components/download-table/index.vue')['default']
    DownTable: typeof import('./src/components/down-table/index.vue')['default']
    Editor: typeof import('./src/components/editor/index.vue')['default']
    EditorElement: typeof import('./src/components/editor-element/index.vue')['default']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    Sider: typeof import('./src/components/sider/index.vue')['default']
    UploadAvatar: typeof import('./src/components/upload-avatar/index.vue')['default']
    UploadTable: typeof import('./src/components/upload-table/index.vue')['default']
    UserInfoModal: typeof import('./src/components/user-info-modal/index.vue')['default']
    VerifyCode: typeof import('./src/components/verify-code/index.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
